# Generated by Django 4.2 on 2023-04-28 05:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('bag_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_identification', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('destiny', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BL', 'Bag Loader'), ('OS', 'Overseer'), ('SA', 'Service Agent'), ('MA', 'Manager')], max_length=2)),
                ('sector', models.CharField(max_length=100)),
                ('access_level', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('load_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_merch', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('destiny', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lcoation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.bag')),
                ('load_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.load')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('hour', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('bag_id', models.ManyToManyField(to='Api.bag')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('bag_id', models.ManyToManyField(to='Api.bag')),
                ('occurrence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.occurrence')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('recovery_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.bag')),
                ('occurrence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.occurrence')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
