# Generated by Django 4.2 on 2023-04-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_FirstMigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_ptr',
        ),
    ]
