# Generated by Django 4.2 on 2023-04-28 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0003_CorrectionMigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='Employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
